<script lang="ts">
  import type { TerminalReportWithCompany } from '$lib/server/db/terminal-reports';
  import ReportHeader from './ReportHeader.svelte';
  import VerdictCard from './VerdictCard.svelte';
  import FrameworkCard from './FrameworkCard.svelte';
  import LedgerStats from './LedgerStats.svelte';
  import BearBull from './BearBull.svelte';
  import CitationAppendix from './CitationAppendix.svelte';
  import ScoreHistoryChart from '$lib/components/charts/ScoreHistoryChart.svelte';
  import { gradeStyle } from './grade';

  interface Props {
    report: TerminalReportWithCompany;
    isOwner: boolean;
    // WP6.1 follow-through stats; null when no ledger data (dev fixture / empty).
    ledger?: { ftr: number | null; onTime: number; late: number; unaccounted: number; total: number } | null;
    // Composite grade trend (oldest→newest); chart renders only when re-graded (≥2 points).
    scoreHistory?: { date: string; score: number; grade: string }[];
  }

  let { report, isOwner, ledger = null, scoreHistory = [] }: Props = $props();

  // Mobile disclaimer expand/collapse — replicates BacktestReport banner pattern.
  let disclaimerExpanded = $state(false);

  const dimensions = $derived(report.dimensions ?? []);
  const trendColor = $derived(gradeStyle(report.composite?.grade ?? 'C').text);
</script>

<div class="min-h-screen bg-[#fcfbf9]">

  <!-- FIXED HEADER -->
  <header class="fixed top-0 left-0 w-full z-[100] h-20 bg-[#fcfbf9]/90 backdrop-blur-md border-b border-[#e5e5e5] px-8 lg:px-12 flex items-center justify-between">
    <div class="flex items-center gap-8">
      {#if isOwner}
        <a href="/dashboard" class="mono-label text-[10px] text-gray-500 no-underline hover:text-black transition-colors flex items-center gap-2">← Dashboard</a>
      {:else}
        <a href="/" class="serif-italic text-2xl font-bold tracking-tight text-gray-900 no-underline">Aslan Terminal</a>
      {/if}
    </div>
    <div class="flex items-center gap-4 flex-wrap justify-end">
      <div class="hidden lg:flex items-center gap-2 px-4 py-2 bg-white border border-[#e5e5e5] rounded-full">
        <span class="w-2 h-2 bg-green-500 rounded-full pulse-status"></span>
        <span class="mono-label text-[10px] tracking-widest text-gray-500">Report Complete</span>
      </div>
      <a href="/api/terminal/report/{report.slug}/pdf" download
        class="hidden sm:block bg-white border border-[#e5e5e5] text-black px-5 py-2 rounded-full mono-label text-[10px] hover:border-black transition-colors duration-300 cursor-pointer no-underline">Export PDF</a>
      <a href="/terminal" class="bg-[#171717] text-white px-6 py-2.5 rounded-full mono-label text-[10px] hover:bg-[#4338ca] transition-colors duration-500 no-underline">New Report →</a>
    </div>
  </header>

  <!-- DISCLAIMER (sticky below fixed header) -->
  <div
    class="sticky top-20 z-40 w-full px-8 lg:px-12 py-2.5 bg-[#fcfbf9]/95 backdrop-blur-sm border-b border-[#e5e5e5] font-sans text-sm text-[#525252] leading-relaxed
           sm:block max-sm:flex max-sm:items-center max-sm:gap-1"
    class:max-sm:flex-col={disclaimerExpanded}
    class:max-sm:items-start={disclaimerExpanded}
  >
    <span
      class="flex-1 min-w-0"
      class:max-sm:overflow-hidden={!disclaimerExpanded}
      class:max-sm:whitespace-nowrap={!disclaimerExpanded}
    >
      This report was generated by AI from public evidence and is for informational
      purposes only. It does not constitute financial advice. Grades are observations
      drawn from cited sources and may be incomplete or inaccurate. Nothing here is a
      recommendation to buy or sell any security. Always do your own research.
    </span>
    <button
      class="hidden max-sm:inline whitespace-nowrap shrink-0 bg-transparent border-none text-[#525252] font-sans text-sm cursor-pointer p-0 leading-relaxed"
      onclick={() => disclaimerExpanded = !disclaimerExpanded}
      aria-label={disclaimerExpanded ? 'Show less' : 'Show more'}
    >{disclaimerExpanded ? 'Show less ▲' : '… Show more ▼'}</button>
  </div>

  <!-- CONTENT -->
  <main class="pt-32 pb-24 px-8 lg:px-12 max-w-[1440px] mx-auto flex flex-col gap-12">

    <ReportHeader
      company={report.company}
      composite={report.composite}
      createdAt={report.created_at}
      rubricVersion={report.rubric_version}
    />

    <!-- Composite grade trend — only once the company has been re-graded (≥2 points). -->
    {#if scoreHistory.length >= 2}
      <section class="bg-white border border-[#e5e5e5] rounded-[2rem] p-8 md:p-10">
        <div class="flex items-baseline justify-between mb-5">
          <span class="mono-label text-[10px] text-gray-400">Score over time</span>
          <span class="font-mono text-[10px] text-gray-400">{scoreHistory.length} grades</span>
        </div>
        <ScoreHistoryChart data={scoreHistory} colorClass={trendColor} height={160} />
      </section>
    {/if}

    <VerdictCard verdict={report.verdict} />

    <!-- Nine health frameworks -->
    <section>
      <span class="mono-label text-[10px] text-[#4338ca] block mb-6">Nine Health Frameworks</span>
      {#if dimensions.length > 0}
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {#each dimensions as d (d.dimension)}
            <FrameworkCard grade={d} {isOwner} />
          {/each}
        </div>
      {:else}
        <p class="font-serif text-lg text-gray-500 italic">No dimension grades recorded.</p>
      {/if}
    </section>

    <LedgerStats startedAt={report.created_at} stats={ledger} />

    <BearBull bearBull={report.bear_bull} />

    <!-- Narrative -->
    {#if report.narrative}
      <section class="bg-white border border-[#e5e5e5] rounded-[2rem] p-8 md:p-10">
        <span class="mono-label text-[10px] text-gray-400 block mb-6">Research Narrative</span>
        <div class="max-w-3xl">
          {#each report.narrative.split('\n\n').filter((p) => p.trim()) as para, i}
            {#if i === 0}
              <p class="font-serif text-2xl text-gray-900 leading-relaxed italic mb-6">{para}</p>
            {:else}
              <p class="font-serif text-lg text-gray-700 leading-relaxed mb-4">{para}</p>
            {/if}
          {/each}
        </div>
      </section>
    {/if}
  </main>

  <CitationAppendix dimensions={report.dimensions} citations={report.citations} />
</div>
