// better-auth managed tables — column names are camelCase to match better-auth's
// internal model field names and the camelCase columns generated by better-auth CLI.
// Do NOT rename columns here without also migrating the database.

import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core"

export const authUser = sqliteTable("user", {
	id:            text("id").primaryKey(),
	name:          text("name").notNull(),
	email:         text("email").notNull().unique(),
	emailVerified: integer("emailVerified", { mode: "boolean" }).notNull(),
	image:         text("image"),
	createdAt:     integer("createdAt", { mode: "timestamp" }).notNull(),
	updatedAt:     integer("updatedAt", { mode: "timestamp" }).notNull(),
	credits:       integer("credits"),
})

export const authSession = sqliteTable("session", {
	id:        text("id").primaryKey(),
	expiresAt: integer("expiresAt", { mode: "timestamp" }).notNull(),
	token:     text("token").notNull().unique(),
	createdAt: integer("createdAt", { mode: "timestamp" }).notNull(),
	updatedAt: integer("updatedAt", { mode: "timestamp" }).notNull(),
	ipAddress: text("ipAddress"),
	userAgent: text("userAgent"),
	userId:    text("userId").notNull().references(() => authUser.id, { onDelete: "cascade" }),
})

export const authAccount = sqliteTable("account", {
	id:                    text("id").primaryKey(),
	accountId:             text("accountId").notNull(),
	providerId:            text("providerId").notNull(),
	userId:                text("userId").notNull().references(() => authUser.id, { onDelete: "cascade" }),
	accessToken:           text("accessToken"),
	refreshToken:          text("refreshToken"),
	idToken:               text("idToken"),
	accessTokenExpiresAt:  integer("accessTokenExpiresAt", { mode: "timestamp" }),
	refreshTokenExpiresAt: integer("refreshTokenExpiresAt", { mode: "timestamp" }),
	scope:                 text("scope"),
	password:              text("password"),
	createdAt:             integer("createdAt", { mode: "timestamp" }).notNull(),
	updatedAt:             integer("updatedAt", { mode: "timestamp" }).notNull(),
})

export const authVerification = sqliteTable("verification", {
	id:         text("id").primaryKey(),
	identifier: text("identifier").notNull(),
	value:      text("value").notNull(),
	expiresAt:  integer("expiresAt", { mode: "timestamp" }).notNull(),
	createdAt:  integer("createdAt", { mode: "timestamp" }).notNull(),
	updatedAt:  integer("updatedAt", { mode: "timestamp" }).notNull(),
})
