import { json, error } from "@sveltejs/kit"
import type { RequestHandler } from "./$types"
import { backtestReports, emailCaptures } from "$lib/server/db/schema"
import { eq, and } from "drizzle-orm"
import { Resend } from "resend"
import { env as privateEnv } from "$env/dynamic/private"
import { env as publicEnv } from "$env/dynamic/public"
const { RESEND_API_KEY } = privateEnv
const PUBLIC_BASE_URL = publicEnv.PUBLIC_BASE_URL

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/

export const POST: RequestHandler = async ({ request, params, cookies, locals }) => {
	let body: unknown
	try {
		body = await request.json()
	} catch {
		return json({ error: "Invalid JSON body" }, { status: 400 })
	}

	const { email } = body as { email?: string }

	if (!email || !EMAIL_RE.test(email)) {
		return json({ error: "Invalid email address" }, { status: 400 })
	}

	const { slug } = params
	const { db } = locals

	// Look up report
	const [report] = await db
		.select({
			id:              backtestReports.id,
			query:           backtestReports.query,
			backtest_result: backtestReports.backtest_result,
		})
		.from(backtestReports)
		.where(
			and(
				eq(backtestReports.slug, slug),
				eq(backtestReports.is_public, true),
				eq(backtestReports.status, "complete")
			)
		)

	if (!report) {
		throw error(404, "Report not found")
	}

	// Check if this email has unlocked any report before (one free backtest per email)
	const [anyCapture] = await db
		.select({ id: emailCaptures.id, report_id: emailCaptures.report_id })
		.from(emailCaptures)
		.where(eq(emailCaptures.email, email))
		.limit(1)

	if (anyCapture) {
		if (anyCapture.report_id !== report.id) {
			// Already used for a different report — prompt them to create an account
			return json({ already_used: true }, { status: 409 })
		}
		// Same report re-visited — just re-set the cookie, no new insert needed
	} else {
		await db.insert(emailCaptures).values({ id: crypto.randomUUID(), email, report_id: report.id })
	}

	// Send confirmation email via Resend (non-blocking — failure does not block access)
	if (RESEND_API_KEY) {
		const resend     = new Resend(RESEND_API_KEY)
		const fromDomain = new URL(PUBLIC_BASE_URL).hostname
		const reportUrl  = `${PUBLIC_BASE_URL}/backtest/${slug}`
		const result     = report.backtest_result as { summary: { total_return_pct: number; event_count: number } }
		const pct        = result.summary.total_return_pct
		const sign       = pct >= 0 ? "+" : "−"
		const pctStr     = `${sign}${(Math.abs(pct) * 100).toFixed(0)}%`
		const eventCount = result.summary.event_count

		const html = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8" /></head>
<body style="font-family: 'IBM Plex Sans', system-ui, sans-serif; background: #0e0e0e; color: #e5e5e5; margin: 0; padding: 40px 20px;">
  <div style="max-width: 560px; margin: 0 auto;">
    <p style="font-size: 14px; color: #888; margin-bottom: 24px;">Aslan Finance</p>

    <h1 style="font-size: 28px; font-weight: 400; font-style: italic; margin: 0 0 16px;">
      Your backtest is ready.
    </h1>

    <p style="font-size: 14px; color: #aaa; margin: 0 0 8px;">Query</p>
    <p style="font-size: 15px; color: #e5e5e5; margin: 0 0 24px;">${report.query}</p>

    <p style="font-size: 36px; font-family: monospace; margin: 0 0 4px; color: ${pct >= 0 ? "#4ade80" : "#f87171"}">
      ${pctStr} across ${eventCount} events
    </p>

    <div style="margin: 32px 0;">
      <a href="${reportUrl}"
         style="display: inline-block; padding: 12px 24px; border: 1px solid #333; color: #e5e5e5; text-decoration: none; font-size: 14px;">
        View Full Report →
      </a>
    </div>

    <p style="font-size: 12px; color: #555; margin-top: 48px; border-top: 1px solid #222; padding-top: 16px;">
      This report was generated by AI and is for informational purposes only. It does not constitute financial advice.
      Past hypothetical performance does not guarantee future results.
    </p>
  </div>
</body>
</html>`

		resend.emails
			.send({
				from:    `Aslan Finance <reports@${fromDomain}>`,
				to:      email,
				subject: "Your Aslan Finance backtest is ready",
				html,
			})
			.catch((err: unknown) => {
				console.error("[capture-email] Resend error (non-fatal):", err)
			})
	} else {
		console.warn("[capture-email] RESEND_API_KEY not set — skipping email send")
	}

	// Set access cookie — 30 days
	cookies.set(`report_access_${slug}`, "1", {
		path:     "/",
		maxAge:   60 * 60 * 24 * 30,
		httpOnly: true,
		sameSite: "lax",
	})

	return json({ success: true })
}
