-- ─────────────────────────────────────────────────────────────────────────────
-- 002_auth.sql  — Replace hand-rolled users/sessions with better-auth tables
-- ─────────────────────────────────────────────────────────────────────────────

-- 1. Drop FK constraints on tables that reference the old `users` table
ALTER TABLE backtest_reports    DROP CONSTRAINT IF EXISTS backtest_reports_user_id_fkey;
ALTER TABLE credit_transactions DROP CONSTRAINT IF EXISTS credit_transactions_user_id_fkey;

-- 2. Drop old hand-rolled auth tables (superseded by better-auth below)
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS users    CASCADE;

-- ─── better-auth managed tables (generated by @better-auth/cli) ──────────────

create table "user" (
  "id"            text        not null primary key,
  "name"          text        not null,
  "email"         text        not null unique,
  "emailVerified" boolean     not null,
  "image"         text,
  "createdAt"     timestamptz default CURRENT_TIMESTAMP not null,
  "updatedAt"     timestamptz default CURRENT_TIMESTAMP not null,
  "credits"       integer
);

create table "session" (
  "id"          text        not null primary key,
  "expiresAt"   timestamptz not null,
  "token"       text        not null unique,
  "createdAt"   timestamptz default CURRENT_TIMESTAMP not null,
  "updatedAt"   timestamptz not null,
  "ipAddress"   text,
  "userAgent"   text,
  "userId"      text        not null references "user" ("id") on delete cascade
);

create table "account" (
  "id"                     text        not null primary key,
  "accountId"              text        not null,
  "providerId"             text        not null,
  "userId"                 text        not null references "user" ("id") on delete cascade,
  "accessToken"            text,
  "refreshToken"           text,
  "idToken"                text,
  "accessTokenExpiresAt"   timestamptz,
  "refreshTokenExpiresAt"  timestamptz,
  "scope"                  text,
  "password"               text,
  "createdAt"              timestamptz default CURRENT_TIMESTAMP not null,
  "updatedAt"              timestamptz not null
);

create table "verification" (
  "id"          text        not null primary key,
  "identifier"  text        not null,
  "value"       text        not null,
  "expiresAt"   timestamptz not null,
  "createdAt"   timestamptz default CURRENT_TIMESTAMP not null,
  "updatedAt"   timestamptz default CURRENT_TIMESTAMP not null
);

create index "session_userId_idx"          on "session"      ("userId");
create index "account_userId_idx"          on "account"      ("userId");
create index "verification_identifier_idx" on "verification" ("identifier");

-- ─── Update dependent tables to reference better-auth's "user"(id) ───────────
-- better-auth uses text PKs; migrate user_id columns from uuid → text.
-- Any existing user_id values reference the now-dropped `users` table,
-- so NULL them out before wiring up the new FK constraint.

UPDATE backtest_reports SET user_id = NULL;

ALTER TABLE backtest_reports
  ALTER COLUMN user_id TYPE text USING user_id::text;

ALTER TABLE backtest_reports
  ADD CONSTRAINT backtest_reports_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL;

-- credit_transactions.user_id is NOT NULL — delete dev rows before re-wiring.
DELETE FROM credit_transactions;

ALTER TABLE credit_transactions
  ALTER COLUMN user_id TYPE text USING user_id::text;

ALTER TABLE credit_transactions
  ADD CONSTRAINT credit_transactions_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE;
